---
- name: Install Docker
  hosts: all
  become: yes 
  vars_files:
    - variables.yml
  

  tasks:
    - name: Check if Docker is installed
      become: true
      command: "docker --version"
      register: docker_check
      ignore_errors: true

    - name: Install Docker 
      include_tasks: Docker.yaml
      tags: install_docker
      when: docker_check.rc != 0
